### ISSUE TITLE
Firefox not working with Symfony 2 and login redirect

### ISSUE THREAD

**Issue by josefvanniekerk** [shakyShane/browser-sync#369]
Copied from: 
http://stackoverflow.com/questions/27522241/browsersync-symfony2-login-redirects-not-working

I'm using [GulpJS][1] with [BrowserSync][2] on a [Symfony 2][3] site, to compile the projects's SCSS files. BrowserSync injects changed CSS into the browsers connected to localhost:3000 and this works really well.

The setup works well for Safari, iOS Simulator, Chrome, Opera and even Internet Explorer running through a virtual machine, however, Firefox is proving to have some issue with redirects.

In Firefox, when I hit **/login**, Symfony redirects to **/login_check** but instead of a successful login, the page simply redirects to **/login** as if nothing happened. No session is created and there is no way to get past the login screen in Firefox.

Looking at the body of /login_check, the following code snippet can be found, and I'm suspecting that this could be something to do with the problem:

    <script type='text/javascript' id="__bs_script__">//<![CDATA[
        document.write("<script async src='/browser-sync/browser-sync-client.1.8.0.js'><\/script>".replace(/HOST/g, location.hostname).replace(/PORT/g, location.port));
    //]]></script>

Debugging with Charles Proxy, the /login_check page shows:

**302 - Client closed connection before receiving entire response** Could it be that BrowserSync is redirecting too early?

I have looked around to try and find a solution for this, but couldn't find any resolution so far.

I've created a Gist with my [gulpfile.js][4]...

Has anyone else had this problem before, and perhaps come up with a workaround?

  [1]: http://gulpjs.com/
  [2]: http://www.browsersync.io/
  [3]: http://symfony.com/
  [4]: https://gist.github.com/josefvanniekerk/dc7fb5cdf617b343d142

**Comment by josefvanniekerk** [comment]
Is there any chance these PR's above can get merged to allow us to fix BrowserSync for FF?

**Comment by shakyShane** [comment]
Hi! Sorry for the delay!

I have some feedback regarding both and I will comment on both ASAP - I'm just in the middle of trying to get a big re-write merged back into master at the moment though which is why I'm not currently on top of merging PRs.

Thanks for your patience.

**Comment by larsbo** [comment]
i think I have the same or a very similar problem. 
I update my development environment to vagrant and now I got the same issue as @josefvanniekerk and only in firefox.
browserSync works fine directly on a local apache and also vagrant works without browserSync. But both together disable page switches in firefox entirely on a shopware (php) project.

**Comment by shakyShane** [comment]
`1.9.0` now has `reloadOnRestart` which you can set to false (which will do as you intended in your PR's).

@josefvanniekerk - Sorry that I didn't use your PR, it was because of two reason. First `--no-reload` is a little bit too vague an option name, to I think new-comers would expect this to stop all reload functionality.

Second, you only added it as a CLI option - I'm pressed for time at the moment so instead of pointing you in the correct direction to fix the PR and make it a default option, I decided in this case it would be quicker to simply implement it myself. 

Thanks for your contribution, I hope the new version fixes this issue for you.
