### ISSUE TITLE
Browsersync Watch all Folders

### ISSUE THREAD

**Issue by AndyF** [shakyShane/browser-sync#380]
Browsersync should have an option to watch all folders (perhaps with  `*` passed in the `--files` option).

**Comment by smith-neil** [comment]
Doesn't **/* watch everything in everything folder?

**Comment by shakyShane** [comment]
@smith-neil  - yes it would, however it should be used with caution (as you won't want it to watch "node_modules" or or vendor directories that have hundreds of files).

Best practice is to narrow down to the folders you want to watch.

For example, to watch HTML files in the root, all CSS files and all JS files, you would want something like

```
browser-sync start --server --files="*.html, css/**, js/**"
```

**Comment by AndyF** [comment]
@smith-neil that doesn't watch `**/**/*` or `**/**/**/*` though.

**Comment by shinnn** [comment]
@smith-neil is right. `**/*` covers `**/**/**/**/**/**/**/**/**/**/**/**/**/**/**/ ... /*`.

**Comment by jdmagic21** [comment]
@shinnn I wish you could use **/* for all the files. This unfotunatly retuns an error.

**Comment by shakyShane** [comment]
@jdmagic21 latest version, if you provide a directory name, all files within will be watched (be careful with this though if you have vendor directories with thousands of files)

```js
bs.init({
    server: 'app'
    files: 'app'
})
```
