### ISSUE TITLE
browser-sync rewrites every redirect

### ISSUE THREAD

**Issue by aaronjensen** [shakyShane/browser-sync#381]
It seems like browser-sync is rewriting off-domain redirects while in proxy mode. For example, if we redirect to `https://www.google.com` from our app, browsersync will rewrite the direct to `https://localhost:8080/` which is not what we want. I couldn't figure out if it was foxy doing this or browser-sync, but it's preventing us from using google oauth in dev mode through browser-sync.

**Comment by shakyShane** [comment]
Confirmed - this is a bug with `node-http-proxy` (which my Foxy modules uses) https://github.com/nodejitsu/node-http-proxy/blob/master/lib/http-proxy/passes/web-outgoing.js#L49-L57

Basically the location header rewriting is being a bit brutal and just applying it to every url.

**Comment by shakyShane** [comment]
Fixed at browser-sync@1.8.3
