### ISSUE TITLE
browser-sync-client js not found

### ISSUE THREAD

**Issue by doshprompt** [shakyShane/browser-sync#383]
I am unable to refresh the browsers programatically through gulp as I get the following error in my console when browser sync runs

Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:1337/browser-sync/browser-sync-client.1.5.7.js

Please help, I am using browser-sync v1.8.3

(I even did rm -rf node_modules, npm cache clean and verified that 1.8.3 is installed locally)

**Comment by shakyShane** [comment]
Can you run 

```shell
browser-sync --version
```

and then

```shell
node node_modules/browser-sync/bin/browser-sync --version
```

and post both results please :)

**Comment by doshprompt** [comment]
Hey, seems like it might have been some sort of browser-side caching issue, I can no longer reproduce. Sorry about that!

**Comment by joelataylor** [comment]
I'm experiencing this issue and don't know how to fix ... I've opened a new browser window (with a new profile) and still get the wrong version of browser-sync-client trying to load. Any suggestions?

**Comment by joelataylor** [comment]
Oops - clearing the browser cache specifically fixed the issue. :+1:

**Comment by themese** [comment]
Had the same issue, just cleared chrome's cache and worked :)
Thanks, joelataylor
