### ISSUE TITLE
Proxy in Firefox Prevents Navigation

### ISSUE THREAD

**Issue by SeeThruHead** [shakyShane/browser-sync#386]
So loading up my site in firefox today and I encountered a problem.
I get interrupted while page was loading.
It reloads the current page instead of following the link.

Seems similar to this
http://stackoverflow.com/questions/27761775/browsersync-prevents-navigation-in-firefox-os-x

**Comment by shakyShane** [comment]
Hi, thanks for letting us know you have a problem. Could you provide a little more detail though? we have some tips here https://github.com/shakyShane/browser-sync/blob/master/CONTRIBUTING.md#-tips-for-a-creating-a-great-issue-report

**Comment by larsbo** [comment]
sounds like [issue #369: Firefox not working with Symfony 2 and login redirect] (https://github.com/shakyShane/browser-sync/issues/369)

**Comment by SeeThruHead** [comment]
Thanks for that, it indeed sounds exactly like issue #369 
I added reloadOnRestart: false and it's working normally now.
I wish I was able to be of more help but I'm not sure how i would go about replication this issue outside of my work project.

**Comment by shakyShane** [comment]
@SeeThruHead - no problem, just happy that it's fixed for you now :)

**Comment by lmartins** [comment]
Thank you, I was also having this problem for a while and `reloadOnRestart: false` also fixed it for me.
