### ISSUE TITLE
Browser not reloading with a vagrant server and gulp

### ISSUE THREAD

**Issue by arthurmuchir** [shakyShane/browser-sync#388]
I have a problem with my vagrant php local server.
Using browser-sync through gulp, I set up browserSync with proxy on my URL (fast.dev).
When I made modification to my files, I see
```
[BS] 1 file changed (main.css)
```
But my browser is not reloading.
I am accessing the website through the URL of browser-sync (localhost:3000).

Any ideas ? I tried a lot without success.
By the way, thanks a lot for your work !

**Comment by arthurmuchir** [comment]
Ok, I had problem in my HTML markup.

**Comment by jiv-e** [comment]
I have the same problem.. How did you resolve it?

**Comment by arthurmuchir** [comment]
My problem was a HTML tag not properly closed

**Comment by jiv-e** [comment]
Ok.. I finally found the reason. Browser-sync doesn't support CSS @import feature.

https://github.com/BrowserSync/browser-sync/issues/10
