### ISSUE TITLE
BrowserSync doesn't detect changes to .ejs (Embedded JavaScript) files

### ISSUE THREAD

**Issue by komplexb** [shakyShane/browser-sync#389]
I'm using [.ejs](http://harpjs.com/docs/development/ejs) files with [HarpJS](http://harpjs.com/) static web server. This command `--files "enrollment/*.ejs, enrollment/css/*"` detects changes to my `.less` files but not to the `.ejs` files. Is there a command or config I can try to get this to work?  

HarpJS compiles the `.ejs` files on the fly so there isn't a build directory I can tell BrowserSync to watch. I just figured once I saved it would diff the file and refresh browsers using the BrowserSync URL.

**Comment by komplexb** [comment]
Solved with: http://ole.michelsen.dk/blog/using-browser-sync-with-harp.html

**Comment by stevenventimiglia** [comment]
Using Gulp, you can also add `gulp.watch('path/**/*.ejs').on('change', browserSync.reload);` to your watch task.
