### ISSUE TITLE
chrome bug: CSS injection requires user interaction to take effect

### ISSUE THREAD

**Issue by joeybaker** [shakyShane/browser-sync#401]
On chrome 42 and chrome 40, injecting CSS doesn't apply the new style sheet until the user interacts with the page. This can be as simple as a mouseover, and the changes are applied. The problem is not in Firefox.

**Comment by shakyShane** [comment]
This is a bug in Chrome, if you open the network tab as you change css files, you'll see that the new css is actually loaded.

I have tried numerous things in the past to force chrome to do a repaint following new css, but I never found a reliable way.

We need to report the bug to the chrome team as it's not something we can solve here :)

**Comment by joeybaker** [comment]
Yea, I figured it was a chrome bug. It's a shame that a force re-paint doesn't work. That was my idea :(
