### ISSUE TITLE
Turn off browsersync reloading for URL path

### ISSUE THREAD

**Issue by austinpray** [shakyShane/browser-sync#415]
### Usecase:

Using browsersync's proxy I have an admin interface located at: `/admin`. I want browsersync turned off when I am in the admin interface. I saw http://www.browsersync.io/docs/options/#option-snippetOptions but after looking at the source and at the implementation of https://github.com/shakyShane/foxy I am not exactly sure if this option is doing what I want or how I would use it.

1. Is it possible to use `ignorePaths` to have browsersync stop watching urls that begin with `/admin`?
2. If not, would you be open to a patch that adds that functionality?

#### Code

- https://github.com/roots/roots/blob/8.0.0/gulpfile.js

#### Discussion

- http://discourse.roots.io/t/gulpfile-with-browsersync/2834/7
- https://github.com/roots/roots/issues/1298

**Comment by shakyShane** [comment]
Sure. This will do exactly what you want.

```js
var browserSync = require("browser-sync");

browserSync({
    proxy: "wordpress.dev",
    snippetOptions: {
        ignorePaths: "wp-admin/**"
    }
});
```

**Comment by jackfearing** [comment]
This may be a dump question but how would I add that snippet into this function?

gulp.task('browser-sync', function() {
    browserSync.init({
		// Specify local domain (i.e Local.domain_name)
        proxy: "local.joints",
		// Don't show any notifications in the browser.
		notify: false,
		// Open the site in Chrome, Firefox & Safari
		//browser: ["Google Chrome", "FireFox", "Safari"]
        browser: ["Safari"]
    });
});

**Comment by shakyShane** [comment]
should be this

```js
gulp.task('browser-sync', function() {
    browserSync.init({
        proxy: "local.joints",
        notify: false,
        browser: ["Safari"],
        snippetOptions: {
            ignorePaths: ["wp-admin/**"]
        },
    });
});
```

Note that `snippetOptions` takes an object - not an array as you put in yours.

**Comment by jackfearing** [comment]
Perfecto! Thanks...
